### ISSUE TITLE
在本地新增测试项目时报错

### ISSUE THREAD

**Issue by ZhaoDong1987** [LinuxSuRen/autotest.platform#2]
打开本地网址，新增项目，点击保存时，报错
系统发生错误，请联系管理员。。。 打开GitHub问题反馈页面，把您遇到的问题记下，我们会尽快修复，谢谢您的贡献！

**Comment by LinuxSuRen** [comment]
已经修正，如果还有问题，请给出更加详细的bug复现步骤。
